### ISSUE TITLE
Beleg 1

### ISSUE THREAD

**Issue by ShuboshaKuro** [ShuboshaKuro/JSF_Beleg#1]
Fehlt noch etwas?

**Comment by yveskaufmann** [comment]
Die Anforderungen der Aufgabe habe wir bereits vollständig implementiert.

Wir brauchen nur noch passende Antworten für die Fragen.
Anbei schon mal meine Vorschläge für die entsprechenden Antworten:
 
- Warum gibt es sowohl die Klasse ToDoListMB als auch die Klasse ToDoList? 
Warum gibt es hier nicht nur eine Klasse? 

   Aufgrund von Separation of Duties, ToDoList dient als Model(MockObject) für ein Liste von ToDo    Objekten, wobei ToDoListMB bisher als UI Model verantwortlich ist eine entsprechende Instanz von ToDoList zu erstellen und bereitzustellen.  

- Verstehen Sie nun, was h:column tut und danach wofür f:facet gebraucht wird ?

   **h:column**:  Rendert eine UIKomponente welche einer einzelnen Spalte von Daten innerhalb einer UIData Komponente wie zum Beispiel **h:dataTable** entspricht. 

  **h:facet**: Registriet eine benannte "facet" innerhalb des umschließenden Elements. Ein "facet" representiert eine benannte Sektion innerhalb einer Container Komponente. Zum Beispiel kann
man innerhalb eines <h:column>-Tags durch <f:facet> eine Über- oder Unterschrift für die Spalte festlegen.

- Erklären Sie noch einmal gegenseitig, warum die markierten ToDos nach dem Drücken von „Speichern“ wieder markiert sind ?

    Da das Facelet **editToDoList.xhtml** bei jedem Aufruf erneut gerendert wird, wobei  die ToDoList über die SessionScoped ManagedBean **ToDoListMB** referenziert wird. Demnach veranlasst das Drücken auf Speichern, dass die Seite neu geladen wird und somit innerhalb der selben Session auch das selbe ToDoList Objekt gerendert wird.

**Comment by ShuboshaKuro** [comment]
Sehr gut, ich wüsste nicht, was ich noch hinzufügen könnte.

おつかれさまでした
